import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'

const Home = ({ results }) => {
  console.log(props)
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <Nav />
      <Results results={results} />
    </div>
  )
}

export const getServerSideProps = async (context) => {
  //const genre = context.query.genre

  const res = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  )

  const results = await res.json()

  return {
    props: {
      results,
    },
  }
}

// export default getStaticPaths = async () => {
//   const genre = context.query.genre

//   const res = await fetch(
//     `https://api.themoviedb.org/3${
//       requests[genre]?.url || requests.fetchTrending.url
//     }`
//   )
//   const results = await res.json()

//   return {
//     paths
//   }

// }

export default Home
